### ISSUE TITLE
Correcciones TP V2.1

### ISSUE THREAD

**Issue by santiagobasso1** [TallerDeProgramacionUTNCDU/TPFinalWindowsForms#4]
Para probar la clase InteraccionApi deberían inyectar como dependencia JSONApiResponse para que sea un test unitario.
La instancia de JSONApiResponse que inyecten debería ser fake, es decir debería devolver un json hardcodeado asi pueden
probar diferentes escenarios.

**Comment by PabloSuarezLapalma** [comment]
### Respuesta del profe

Los escenarios a probar deben surgir de los datos devueltos y que se utilicen en la aplicación. 

Como la clase ya está confeccionada creo que lo conveniente es lo siguiente
- Crear Test de camino feliz
Crear el test inyectando una instancia fake de JSONApiResponse que devuelva la estructura que esperan y verificar que los DTOs creados sean lo que uds esperan.
- Crear tests casos excepcionales.
Un caso puede ser que no devuelva info. 
Si no conocen otro caso relacionado lo que pueden hacer es seguir desarrollando y probando la app, y cuando se encuentren con un problema relacionado a datos de la API que no tenían en cuenta, generen el test para que falle y después solucionen el error.

Saludos.
